name: cd-workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: ${{secrets.AWS_REGION}} 

      - name: install terraform
        uses: hashicorp/setup-terraform@v4

      - name: terraform init
        working-directory: terraform-infra
        run: terraform init -input=false

      - name: terraform apply
        working-directory: terraform-infra
        run: terraform apply -var="image_tag=null" -input=false --auto-approve 

      - name: read terraform output
        id: tf_outputs
        working-directory: terraform-infra
        run: |  
            echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT
            echo "repository_url=$(terraform output -raw repository_url)" >> $GITHUB_OUTPUT

      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build docker image
        run: |
            docker build -t ${{ steps.tf_outputs.outputs.repository_url }}:${{ github.sha }} -f Dockerfile .

      - name: push docker image to ECR
        run: docker push ${{ steps.tf_outputs.outputs.repository_url }}:${{ github.sha }}

      - name: push model to s3
        run: aws s3 cp ml_pipiline.pkl s3://${{ steps.tf_outputs.outputs.bucket_name }}

      - name: deploy lambda 
        working-directory: terraform-infra
        run: terraform apply -var="deploy_lambda=true" -var="image_tag=${{ github.run_number }}" -input=false --auto-approve

      - name: Show Deployment URL
        working-directory: terraform-infra
        run: |
          echo "API URL: $(terraform output -raw api_gateway_url)"